sudo: false
language: python
env:
    - TOXENV=py26-ansible_stable
    - TOXENV=py27-ansible_stable
# ansible-2.0 support coming soon
#    - TOXENV=py26-ansible_devel
#    - TOXENV=py27-ansible_devel
install:
  - pip install -r test-requirements.txt --use-mirrors
script:
  - tox
addons:
  apt_packages:
      - pandoc
after_success:
  coveralls
