sudo: false
language: python
sudo: required # needed for test_become
env:
    - TOXENV=py27-ansible_v24
    - TOXENV=py27-ansible_v25
    - TOXENV=py27-ansible_v26
    - TOXENV=py27-ansible_devel
    - TOXENV=py36-ansible_devel
install:
    - pip install -r test-requirements.txt
script:
    - tox
before_script:
    - TOXENV=lint tox
after_success:
    - TOXENV=coveralls tox
addons:
  apt_packages:
    - pandoc
