sudo: false
language: python
sudo: required # needed for test_become
env:
    - TOXENV=py26-ansible_v19
    - TOXENV=py27-ansible_v19
    - TOXENV=py26-ansible_stable
    - TOXENV=py27-ansible_stable
    - TOXENV=py26-ansible_devel
    - TOXENV=py27-ansible_devel
install:
  - pip install -r test-requirements.txt --use-mirrors
script:
  - tox
addons:
  apt_packages:
      - pandoc
after_success:
  coveralls
