sudo: false
language: python
env:
    - TOXENV=py26-ansible_stable
    - TOXENV=py26-ansible_devel
    - TOXENV=py27-ansible_stable
    - TOXENV=py27-ansible_devel
install:
  - pip install -r test-requirements.txt --use-mirrors
script:
  - tox
addons:
  apt_packages:
      - pandoc
